### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by S-L-Murphey** [S-L-Murphey/Bugbo#1]
As a user I would like to be able to logout of the system so that I can ensure that no one else who uses my computer will have access to my Bugbo account.

**Given** an authenticated user is in the Bugbo application
**When** they select the Logout option from the menu
**Then** they should be logged out of the system
**And** they should be directed to the home page

**Comment by davidhenley** [comment]
Are you going to use Local Storage for this or Cookies?

**Comment by S-L-Murphey** [comment]
Going with Local Storage for this one with DRF Token Authentication on the back end. I'm don't believe i'm familiar with JWT tokens as of yet.

**Comment by davidhenley** [comment]
DRF Token Authentication uses JWT in the background so pretty much the same thing.
